version: "3.9"
services:
  backend:
    build: ./server
    volumes:
      - ./server/boligbirding.db:/app/boligbirding.db
      - ./server/downloads:/app/downloads
      - ./web:/app/web:ro
    ports:
      - "8001:8000"
    environment:
      - TZ=Europe/Copenhagen